services:
  postgres:
    image: postgres:14
    container_name: pvz_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pvz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: pvz_app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pvz
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - JWT_SECRET_KEY=avito_secret_key
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: